config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users
  
  post '/users/new', to: 'users#create'
  get '/contacts/:id', to: 'contacts#index'
  get '/contacts/:user_id/new', to: 'contacts#new'
  post '/contacts/:id', to: 'contacts#create'
  delete '/contacts/:id', to: 'contacts#destroy'
  patch '/contacts/:id/:user_id', to: 'contacts#update'
  resources :users, :contacts

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    #can :manage, :all if user.access_group == "admin"
    #can :read, :all if user.access_group == "guest"
    
    
    if user.access_group == "admin"
      can :manage, :all 
    else #guest
      can :show, :all, id: user.id
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :user
	
	validates :phone_number, :details, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :contacts, dependent: :destroy #:dependent => :destroy
  
  devise :database_authenticatable, :registerable,
				:recoverable, :rememberable, :trackable, :validatable
				
	validates :name, :email, presence: true
	
	GROUP = ['admin','guest']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
	 
	rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end 
	
  def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
			:name, :access_group, :email, :password, :password_confirmation
		)}
		 
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(
			:name, :access_group, :current_password
		)}
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_filter :authenticate_user!, only: :index
	
	def index
		@user = User.find(params[:id])
		@contacts = @user.contacts.order(updated_at: :desc)
		
		#binding.pry
		
		authorize! :show, @user
		respond_to do |format|
			format.js
			format.html
		end
	end
	
	def show
		#code
	end
	
	def new
		@contact = Contact.new
		#@user = User.find(params[:user_id])
		#@contact_params = Contact.where(user_id: params[:user_id])
	end
	
	def edit
    @contact = Contact.find(params[:id])
    #@user = User.joins(:contacts).where("contacts.id = #{params[:id]}")
    respond_to do |format|
			format.js
		end
    #binding.pry
    #authorize! :manage, @contact
  end
	
	def create
		#byebug
		@contact = Contact.new(contact_params)
		@user = User.find(@contact.user_id)
		@contacts = @user.contacts
		saved = @contact.save
		
		respond_to do |format|
			format.js
			format.html do
				if saved
					redirect_to contact_path(@contact.user_id)
				else 
					render :new
				end
			end
		end
	end

	def update
		#binding.pry
		@contact = Contact.find(params[:id])
    @user = User.find(params[:user_id])
    @contacts = @user.contacts
    updated = @contact.update(contact_params)
    
    respond_to do |format|
			format.js
			format.html do
				if @contact.errors.blank?
					if updated
						#flash[:notice] = "Data has been updated"
						redirect_to contact_path(@contact.user_id)
					end
				else
					render :edit
					#flash[:notice] = "Contact has been successfully updated."
				end
			end
		end
	end
	
	def destroy
		@contact = Contact.find(params[:id])
		@user = User.find(params[:user_id])
		@contact.destroy
		flash[:notice] = "Data has been removed"
		#redirect_to :back
		redirect_to contact_path(@user.id), notice: "Contact has been successfully destroy."
	end
	
	private
  def contact_params
    params.require(:contact).permit(:details, :phone_number, :user_id)
  end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_filter :authenticate_user!, :except => [:show, :new]
  	before_filter :authenticate_user!, :only => :index

  def index
    #@user = User.all
    #@users = User.order(id: :asc)
    @count = Contact.count 
    @users = User.find_by_sql(
      "select t1.*, count(distinct t2.id) as total
      from users t1
      left join contacts t2 on t1.id = t2.user_id
      group by t1.id
      order by t1.id"
    )
    if cannot? :manage, @users
      redirect_to contact_path(current_user.id)
    end
  end
   
  def show
    @user = User.find(params[:id])
    authorize! :show, @user
    #if can? :read, @user
    #   unless @user == current_user
    #    redirect_to users_path, :alert => "Access denied."
    #  end
    #end
    
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
    #binding.pry
    authorize! :manage, @user
  end
  
  def create
    @user = User.new(user_params)
    authorize! :manage, @user
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if params[:user][:password].blank?
      @user.update_without_password(user_params)
    else
      @user.update(user_params)
    end
    
    if @user.errors.blank?
      redirect_to users_path, :notice => "User information updated successfully."
    else
      render :edit
    end
    
    #if @user.update(user_params)
    #  redirect_to users_path
    #else
    #  render 'edit'
    #  #redirect_to edit_user_path
    #  #flash[:alert] = 'error'
    #end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Data have been removed"
    redirect_to :back
  end
  
  #binding.pry
  private
  def user_params
    params.require(:user).permit(:name, :access_group, :email, :password, :password_confirmation)
  end
  
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_data_grid.html.erb
<thead>
  <tr>
    <th class="t_header">Id</th>
    <th class="t_header">Phone Number</th>
    <th class="t_header">Details</th>
    <th class="t_header">Action</th>
    <!--<#% if can? :manage, @user %>
      <th class="">Other Action</th>
    <#% end %>-->
  </tr>
</thead>  
<tbody>
<% @contacts.order(updated_at: :desc).each do |contact_str| %>

<tr>
  <td><%= contact_str.id %></td>
  <td><%= contact_str.phone_number %></td>
  <td><%= contact_str.details %></td>
  <td>
    <%= link_to edit_contact_path(contact_str.id), title: 'edit contact', remote: true do %>
      <span class="glyphicon glyphicon-pencil"></span>
      edit
    <% end %>
    <br />
    <%= link_to contact_path({ id: contact_str.id, user_id: contact_str.user_id }), #contact_path(contact_str.id),
      method: :delete, title: 'remove contact',
      data: { confirm: 'Are you sure remove this data?' }, class: 'delete_action' do %>
      <span class="glyphicon glyphicon-trash"></span>
      delete
    <% end %>
  </td>
</tr>

<% end %>
</tbody>

app/views/contacts/_edit.html.erb
<h3><%= "#{@contact.id}#" %> Edit contact here</h3>

<%= form_for :contact,
url: contact_path({id: @contact.id, user_id: @contact.user_id}),
role: :form,
method: :patch,
remote: true do |f| %>
    
  <div class="form-group">  
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>
  
  <%= link_to 'Cancel', contact_path(@contact.user_id), class: "btn btn-default left", remote: true %>
  <%= f.submit 'Save', :class => 'button right' %>
<% end %>

app/views/contacts/_error.html.erb
<% if @contact.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@contact.errors.count, "error") %> prohibited
				this Contact from being saved:
			</h2>
			<ul>
				<% @contact.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
<% end %>

app/views/contacts/_new.html.erb
<h3>Create contact here</h3>

<%= form_for :contact,
url: contact_path(@user.id),
role: :form,
remote: true do |f| %>
  <%= hidden_field_tag 'contact[user_id]', @user.id %>
  <div class="form-group">  
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>
  
  <%= link_to 'Cancel', contact_path(@user.id), class: "btn btn-default left", remote: true %>
  <%= f.submit 'Add', class: 'button right' %>

<% end %>

app/views/contacts/create.js.erb
$("#form_error").html("<%= j (render 'error') %>");
$("#render_js").html("<%= j (render 'data_grid') %>");

app/views/contacts/edit.js.erb
$("#form_contact").html("<%= escape_javascript(render 'edit') %>");

app/views/contacts/index.html.erb
<div class="authform contact">
  <div id="form_error"></div>
  <div id="form_contact">
    <%= render 'new' %>
  </div>
</div>

<div class="container">
  <div class="row">
    
    <% if can? :manage, @user %>
      <%= link_to 'User list', users_path %> 
       <span class="glyphicon glyphicon-backward"></span>
       Back to
    <% end %>
    
    <h3>Contact &raquo; <%= "#{@user.id}##{@user.name}" %></h3>
    
    <%#= link_to "#{@user.id}/new", class: "btn btn-primary custom", title: "new" do %>
      <!--<span class="glyphicon glyphicon-plus-sign"></span>
      Add new-->
    <%# end %>
    
    <div class="column">
      <!--<a href="#" class="btn btn-primary custom" role="button">Button</a>-->
      
      <table class="table" id="render_js">
        <%= render 'data_grid' %>
      </table>
      
      <!--<div id="grid_render"></div>-->
      <!--<p><%#= link_to 'Users:', users_path %> <%= User.count %> registered</p>-->
    </div>
  </div>
</div>

</script>

app/views/contacts/index.js.erb
$("#form_error").html("");
$("#form_contact").html("<%= escape_javascript(render 'new') %>");

app/views/contacts/update.js.erb
$("#render_js").html("<%= escape_javascript(render 'data_grid') %>");
$("#form_error").html("<%= escape_javascript(render 'error') %>");

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%#= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <% if can? :manage, @user %>
    <li><%= link_to 'Users', users_path %></li>
  <% elsif can? :read, @user %>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <% end %>
  <li><%#= link_to 'Add User', new_user_registration_path  %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Contact" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<td><%= user.id %></td>
<td><%= user.name %></td>
<td><%= user.email %></td>
<td><%= user.total %></td>
<td><%= user.access_group %></td>
<% if can? :manage, user %>
  <td>
    <%= link_to edit_user_path(user.id), title: 'edit user' do %>
      <span class="glyphicon glyphicon-pencil"></span>
    <% end %>
    &nbsp;
    <%= link_to user, title: 'show detail' do %>
      <span class="glyphicon glyphicon-search"></span>
    <% end %>
    &nbsp;
    <%= link_to contact_path(user.id), title: 'show contact' do %>
      <span class="glyphicon glyphicon-user"></span>
    <% end %>
    &nbsp;
    <%= link_to user_path(user.id), title: 'remove user',
      method: :'delete', data: {confirm: 'Are you sure remove this data?'} do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </td>
<% end %>

app/views/users/edit.html.erb
<div class="authform">
  <h3>Edit User Information<%#= @user.name %></h3>
  
  <%= form_for :user, url: user_path(@user), method: :patch, role: :form do |f| %>
      
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@user.errors.count, "error") %> prohibited
          this User from being saved:
        </h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :access_group %> &raquo;
      <%= f.select(:access_group, ['admin','guest'], class: 'form-control')  %>
    </div>
    
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    
    <fieldset>
      <p>Leave these fields blank if you don't want to change your password.</p>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </fieldset>
    
    <%= link_to 'Cancel', users_path, class: "btn btn-default left" %>
    <%= f.submit 'Update', :class => 'button right' %>
  
  <% end %>
  
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users <%= current_user.name %> (@Login as <%= current_user.access_group %>)</h3>
    
    <%= link_to new_user_path, class: "btn btn-primary custom", title: "new" do %>
      <span class="glyphicon glyphicon-plus-sign"></span>
      Add new
    <% end %>
    
    <div class="column">
      
      <table class="table">
        <thead>
          <tr>
            <th class="t_header">Id</th>
            <th class="t_header">Name</th>
            <th class="t_header">Email</th>
            <th class="t_header">Contact</th>
            <th class="t_header">Group</th>
            <% if can? :manage, @user %>
              <th class="t_header">Action</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="3"><b>Total contact:</b></td>            
            <td><b><%= @count %></b></td>
            <td colspan="2"></td>
          </tr>
        </tfoot>
      </table>
      
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="authform">
  <h3>New User</h3>
  <%= form_for @user, url: '/users/new', method: :post do |f| %>
      
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@user.errors.count, "error") %> prohibited
          this Contact from being saved:
        </h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :group %> <br />
      <%= f.select(:access_group, ['admin','guest'], class: 'form-control')  %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <%= hidden_field_tag 'user[password]', '1234567890' %>
    <%= link_to 'Cancel', users_path, class: "btn btn-default left" %>
    <%= f.submit 'Create', :class => 'button right' %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= link_to 'User list', users_path %>
<span class="glyphicon glyphicon-backward"></span>
Back to

<h3>User Information</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

<%= @user.inspect %>